language: python
python:
  - 3.9
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
  - cp contrib/env-sample .env
script:
  - flake8
  - pytest tests --cov=tests
  - pipenv run pytest
after_success:
  - codecov